<a href="https://colab.research.google.com/github/Priyam8210/CyberLab/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:



import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
tr_data = (pd.read_csv("/content/drive/MyDrive/Colab Notebooks/emnist-letters-train.csv"))
te_data = (pd.read_csv("/content/drive/MyDrive/Colab Notebooks/emnist-letters-test.csv"))

In [ ]:
tr_data.isnull().sum()

23       0
0        0
0.1      0
0.2      0
0.3      0
        ..
0.411    0
0.412    0
0.413    0
0.414    0
0.415    0
Length: 785, dtype: int64

In [ ]:
tr_data.info()
te_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88799 entries, 0 to 88798
Columns: 785 entries, 23 to 0.415
dtypes: int64(785)
memory usage: 531.8 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14799 entries, 0 to 14798
Columns: 785 entries, 1 to 0.557
dtypes: int64(785)
memory usage: 88.6 MB


In [ ]:
tr_data.head()

23  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.406  0.407  0.408  \
0   7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  16  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  15  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  23  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  17  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.409  0.410  0.411  0.412  0.413  0.414  0.415  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [ ]:
te_data.head()

1  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.548  0.549  0.550  \
0  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.551  0.552  0.553  0.554  0.555  0.556  0.557  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [ ]:
train_data = np.array(tr_data)
test_data = np.array(te_data)

In [ ]:
train_label = train_data[:,0]
print(train_label.shape)
train_label.shape = (88799,1) 
print(train_label)

test_label = test_data[:, 0]
print(test_label.shape)
test_label.shape= (14799, 1)
print(test_label)

(88799,)
[[ 7]
 [16]
 [15]
 ...
 [ 1]
 [23]
 [12]]
(14799,)
[[ 1]
 [ 1]
 [ 1]
 ...
 [19]
 [19]
 [19]]


In [ ]:
X_train = train_data[:, 1:]
X_test = test_data[:,1:]




In [ ]:
print(X_train)
X_train.shape


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(88799, 784)

In [ ]:
X_test.shape

(14799, 784)

In [ ]:
X_train = X_train/255
X_test = X_test/255

In [ ]:
def ecludian(X, Y):
  dist = np.sqrt(np.sum(((X- Y)**2),1))
  dist.shape = (np.size(X, 0), 1)
  return dist

In [ ]:
def KNN_(X, X_te, tr_label, K):
  n = np.size(X_te, 0)
  pred = []
  for points in X_te:
    #finding ecludian distance
    dist_val = ecludian(X_train, points)
    dist_lab = np.concatenate((tr_label, dist_val), axis =1)

    #sorting
    dist_lab = np.argsort(dist_lab[:, 0])
    
    #getting sorted label
    sort_label = tr_label[dist_lab]

    #getting top K label
    Kth_near = sort_label[:K]
    
    #finding Mode for label
    vals,counts = np.unique(Kth_near, return_counts=True)
    index = np.argmax(counts)

    #prediction label
    prediction = vals[index]
    pred = np.append((pred, prediction), 1)

  return pred

In [ ]:
pred = KNN_(X_train, X_test, train_label, K=27)

In [ ]:
def accuracy(pred, Y):
  n = np.size(Y, 0)
  j=0
  for i in range(n):
    if pred[i] == Y[i]:
      j = j+1

  return j/n

In [ ]:
accuracy(pred, test_label)